name: flexi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # localization language
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # network Service
  http: ^0.13.4
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  logger: ^1.1.0
  #social login
  flutter_facebook_auth: ^4.4.1+1
  google_sign_in: ^5.4.2
  # to pick date and time
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_datepicker: ^20.3.49
  # to pick Image
  image_picker: ^0.8.6
  #show image and Cached
  cached_network_image: ^3.2.0
  #state managment
  provider: ^6.0.3
  # google font style
  google_fonts: ^3.0.1
  #local database
  shared_preferences: ^2.0.12
  #firebase use
  firebase_storage:
  firebase_core: ^1.14.1
  cloud_firestore:
  firebase_auth: ^3.3.14
  #videos and Audio
  #  video_player: ^2.4.5
  #  audioplayers: ^1.0.1
  #  record: ^4.1.1
  # pick time
  #  date_time_picker: ^2.1.0
  #pick country code
  country_code_picker: ^2.0.2
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.1.1
  syncfusion_flutter_sliders: ^20.3.48
  syncfusion_flutter_charts: ^20.3.48
  custom_pop_up_menu: ^1.2.4
  flutter_rating_bar: ^4.0.1
  awesome_dialog: ^3.0.2
  number_to_word_arabic: ^0.0.8
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^7.4.0
  sweet_nav_bar: ^1.0.5
  #permission_handler
  #  permission_handler: ^10.0.0
  #  flutter_screenutil: 5.0.0
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.6
  convex_bottom_bar: ^3.0.0
  fluttertoast: ^8.0.9
  device_info_plus: ^4.1.2
  qr_flutter: ^4.0.0
  #  flutter_card_scanner_latest: ^1.0.5
  #  easy_card_scanner: ^1.1.0
  #map
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  overlay_support: ^2.1.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  test: ^1.21.1


flutter:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/arabic/(A) Arslan Wessam A (A) Arslan Wessam A.ttf

          weight: 500

    - family: arslan
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 600

        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500

        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
